# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boundary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  db-init:
    image: hashicorp/boundary-enterprise
    command: ["database", "init", "-config", "/boundary/config.hcl"]
    volumes:
      - ./boundary:/boundary
    environment:
      - BOUNDARY_POSTGRES_URL=postgresql://postgres:postgres@db/boundary?sslmode=disable
      - BOUNDARY_LICENSE=${BOUNDARY_LICENSE}
    cap_add:
      - IPC_LOCK
    depends_on:
      db:
        condition: service_healthy

  boundary:
    image: hashicorp/boundary-enterprise
    hostname: "boundary"
    command: ["server", "-config", "/boundary/config.hcl"]
    volumes:
      - ./boundary:/boundary
    ports:
      - "9200:9200"
      - "9201:9201"
      - "9202:9202"
    environment:
      - BOUNDARY_POSTGRES_URL=postgresql://postgres:postgres@db:5432/boundary?sslmode=disable
      - BOUNDARY_LICENSE=${BOUNDARY_LICENSE}
    depends_on:
      db-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://boundary:9200"]
      interval: 3s
      timeout: 5s
      retries: 5

  # Boundary controller is the last service to start and may not be fully up
  # by the time the docker compose command returns, so we force a wait by
  # depending a placeholder on the controller healthcheck
  wait:
    image: busybox:latest
    command: ["sleep", "1"]
    depends_on:
      boundary:
        condition: service_healthy

  # Private Database Targets - not exposed to host network, only available via Boundary
#  cassandra:
#    image: bitnami/cassandra:latest
#
#  mysql:
#    image: mariadb
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
#
#  redis:
#    image: redis
#
#  mssql:
#    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
#    environment:
#      - 'ACCEPT_EULA=Y'
#      - 'SA_PASSWORD=yourStrong(!)Password'